defaults:
  - paths: default
  - wandb: wandb_config
  - data: xela
  - algorithm: byol_alexnet
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

model_info:
  tiny:
    embed_dim: 192
    depth: 12
    num_heads: 3
    mlp_ratio: 4
  small:
    embed_dim: 384
    depth: 12
    num_heads: 3
    mlp_ratio: 4
  base:
    embed_dim: 768
    depth: 12
    num_heads: 12
    mlp_ratio: 4
  large:
    embed_dim: 1024
    depth: 24
    num_heads: 16
    mlp_ratio: 4

seed: 42
model_size: base
model_embed_dim: ${model_info.${model_size}.embed_dim}
resume_id: ~
ckpt_path: ~
experiment_name: default_${model_size}

trainer:
  max_epochs: ~
  grad_clip_norm: 10.0
  validation_frequency: 10
  checkpoint_frequency: 10
  log_frequency: 500
  save_checkpoint_dir: ${paths.output_dir}/checkpoints

hydra:
  job:
    id: ${now:%Y.%m.%d}-${now:%H-%M}
  run:
    dir: ${paths.log_dir}/${experiment_name}/${hydra.job.id}
