# @package _global_

model_size: tiny

img_size: [224, 224]
img_chans: 6
img_patch_size: 16

mic_size: [224, 256]
mic_chans: 1
mic_patch_size: 16

imu_size: 224
imu_chans: 3
imu_patch_size: 4

pressure_size: 224
pressure_chans: 1
pressure_patch_size: 4

sensor_sizes:
  img: ${img_size}
  mic: ${mic_size}
  imu: ${imu_size}
  pressure: ${pressure_size}

sensor_chans:
  img: ${img_chans}
  mic: ${mic_chans}
  imu: ${imu_chans}
  pressure: ${pressure_chans}

patch_sizes:
  img: ${img_patch_size}
  mic: ${mic_patch_size}
  imu: ${imu_patch_size}
  pressure: ${pressure_patch_size}

fusion_type: bottleneck

normalization:
  img:
    avg: [0.09562227, 0.26593734, 0.32464101]
    std: [0.08179263, 0.17255498, 0.18509875]
    div: 1
  mic_fbank:
    normalize:
      _partial_: True
      _target_: tactile_ssl.data.d360.utils.normalize_mic_fbank
    avg: null
    std: null
    div: 2
    range: [-32, 32]
  imu_acc:
    div: 4
  pressure:
    normalize:
      _partial_: True
      _target_: tactile_ssl.data.d360.utils.normalize_pressure
    avg: null
    std: null
    div: 2
    range: [-16, 16]

attn_cls: Attention

encoder:
  _target_: tactile_ssl.model.d360_transformer.dit_${model_size}
  use_img: true
  use_mic: true
  use_imu: true
  use_pressure: true
  sensor_sizes: ${sensor_sizes}
  sensor_chans: ${sensor_chans}
  patch_sizes: ${patch_sizes}
  num_register_tokens: 1
  fusion_type: ${fusion_type}
  fusion_layer: 8
  num_bottlenecks: 4
  drop_path_rate: 0.3
  pos_embed_fn: sinusoidal
  normalization: ${normalization}
  attn_class:
    _partial_: True
    _target_: tactile_ssl.model.layers.${attn_cls}
