# @package _global_
model_size: tiny
encoder:
  _target_: tactile_ssl.model.xela_${model_size}
  in_dim: 368 # total number of xela sensors in hand
  in_chans: 6 # 3 xela mag channels + 3 position channels
  sequence_length: 10
  time_chunk_size: 10
  num_register_tokens: 1
  pos_embed_fn: learned
  with_masktoken: True
  drop_path_rate: 0.3
  drop_path_uniform: True
  normalization:
  causal: False
