_target_: tactile_ssl.algorithm.D360DINOModule
encoder:
  _target_: tactile_ssl.model.d360_transformer.dit_small
  use_img: ${use_img}
  use_mic: ${use_mic}
  use_imu: ${use_imu}
  use_pressure: ${use_pressure}
  sensor_sizes: ${sensor_sizes}
  sensor_chans: ${sensor_chans}
  patch_sizes: ${patch_sizes}
  num_register_tokens: 1
  fusion_type: ${fusion_type}
  fusion_layer: 8
  num_bottlenecks: 4
  drop_path_rate: 0.3
  pos_embed_fn: learned
  normalization: ${data.sensor.d360.dataset.config.normalization}
  attn_class:
    _partial_: True
    _target_: tactile_ssl.model.layers.${attn_cls}
dino_head:
  _partial_: True
  _target_: tactile_ssl.model.layers.DINOHead
  out_dim: 65536

num_global_masks: 2
num_local_masks: 8
global_mask_scales:
  img: [0.48, 1.0]
  mic: [0.48, 1.0]
  imu: [0.48, 1.0]
  pressure: [0.48, 1.0]
local_mask_scales:
  img: [0.1, 0.48]
  mic: [0.1, 0.48]
  imu: [0.1, 0.48]
  pressure: [0.1, 0.48]
min_keep_num_patches:
  img: 4
  mic: 4
  imu: 4
  pressure: 4

moving_average_decay: 0.998
allow_mask_overlap: True
teacher_temp: [0.04, 0.07]
teacher_warmup_epochs: 10

optim_cfg:
  _partial_: True
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 0.05

lr_scheduler_cfg:
  _partial_: True
  _target_: tactile_ssl.model.custom_scheduler.WarmupCosineScheduler
  final_lr: 1.0e-6
  start_lr: 1e-5
  warmup_epochs: 30

wd_scheduler_cfg:
  _partial_: True
  _target_: tactile_ssl.model.custom_scheduler.CosineWDSchedule
  final_weight_decay: 0.4
  ref_weight_decay: 0.04

online_probes:
  - _target_: tactile_ssl.probe.OnlineProbeModule
    probe_name: "reconstruction"
    decoder:
      _target_: tactile_ssl.model.d360_transformer.dit_decoder
      modal_chans: 768
      embed_dim: 192
      depth: 4
      num_heads: 12
      use_img: ${use_img}
      use_mic: ${use_mic}
      use_imu: ${use_imu}
      use_pressure: ${use_pressure}
      sensor_sizes: ${sensor_sizes}
      sensor_chans: ${sensor_chans}
      patch_sizes: ${patch_sizes}
      fusion_type: ${fusion_type}
      fusion_layer: 3
      num_bottlenecks: 4
      normalization: ${data.sensor.d360.dataset.config.normalization}
    loss_fn:
      _target_: torch.nn.MSELoss

online_probes_lrs: [1e-4]

loss_weight_reconstruction:
  img: 1
  mic: 1
  imu: 1
  pressure: 1e-4

log_freq_reconstruction: 100
