_target_: tactile_ssl.algorithm.XelaMAEModule
encoder:
  _target_: tactile_ssl.model.xela_base
  in_dim: 368 # total number of xela sensors in hand
  in_chans: 3 # 3 xela mag channels + 3 position channels
  sequence_length: 1
  time_chunk_size: 1
  num_register_tokens: 1
  pos_embed_fn: learned
  with_masktoken: True
  drop_path_rate: 0.3
  drop_path_uniform: True
  normalization: ${data.normalization}
  causal: False

mask_type: random
mask_ratio: 0.75

decoder:
  _target_: tactile_ssl.probe.reconstruction.SignalMaskDecoder
  in_dim: ${algorithm.encoder.in_dim}
  in_chans: ${algorithm.encoder.in_chans}
  sequence_length: ${algorithm.encoder.sequence_length}
  time_chunk_size: ${algorithm.encoder.time_chunk_size}
  input_embed_dim: ${model_embed_dim}
  embed_dim: 192
  depth: 4
  num_heads: 12
  pos_embed_fn: sinusoidal
  mlp_ratio: 4.0
  qkv_bias: True


optim_cfg:
  _partial_: True
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 0.05

lr_scheduler_cfg:
  _partial_: True
  _target_: tactile_ssl.model.custom_scheduler.WarmupCosineScheduler
  steps_per_epoch: ???
  T_max: ???
  final_lr: 1.0e-6
  start_lr: 1e-5
  warmup_epochs: 30

wd_scheduler_cfg:
  _partial_: True
  _target_: tactile_ssl.model.custom_scheduler.CosineWDSchedule
  final_weight_decay: 0.4
  ref_weight_decay: 0.04
  T_max: ???

online_probes:
  - _target_: tactile_ssl.probe.online_probe.OnlineProbeModule
    probe_name: "object_classification"
    decoder:
      _target_: tactile_ssl.probe.classification.LinearClassifier
      input_embed_dim: ${model_embed_dim}
      classes: ${data.object_classes}
      class_weights: ${data.object_class_weights}
    loss_fn:
      _partial_: true
      _target_: torch.nn.CrossEntropyLoss

online_probes_lrs: [1e-4]

