_target_: tactile_ssl.algorithm.BYOLModule

backbone:
  _target_: tactile_ssl.model.AlexnetWrapper
projector:
  _target_: tactile_ssl.algorithm.byol.MLP
  input_dim: 9216
  output_dim: 1024
decoders:
  - _target_: tactile_ssl.algorithm.byol.ReconstructionDecoder
    input_dim: 1024
  - _target_: tactile_ssl.algorithm.byol.ClassificationDecoder
    input_dim: 1024
    classes: ${data.object_classes}
    class_weights: ${data.object_class_weights}
augment_fn:
  _target_: tactile_ssl.data.xela_tdex.utils.get_tactile_augmentations
  img_size: [224, 224]
optim_cfg:
  _partial_: True
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 0.05

moving_average_decay: [0.994, 1.0]
decoder_lrs: [1e-4, 1e-4]
image_size: 224

lr_scheduler_cfg:
  _partial_: True
  _target_: tactile_ssl.model.custom_scheduler.WarmupCosineScheduler
  steps_per_epoch: ???
  T_max: ???
  final_lr: 1.0e-6
  start_lr: 1e-5
  warmup_epochs: 30

wd_scheduler_cfg:
  _partial_: True
  _target_: tactile_ssl.model.custom_scheduler.CosineWDSchedule
  final_weight_decay: 0.4
  ref_weight_decay: 0.04
  T_max: ???


# online_probes:
#   - _target_: tactile_ssl.probe.OnlineProbeModule
#     probe_name: "reconstruction"
#     decoder:
#       _target_: tactile_ssl.probe.reconstruction.SignalDecoderBase
#       in_dim: ${algorithm.encoder.in_dim}
#       in_chans: ${algorithm.encoder.in_chans}
#       sequence_length: ${algorithm.encoder.sequence_length}
#       time_chunk_size: ${algorithm.encoder.time_chunk_size}
#       input_embed_dim: ${model_embed_dim}
#       embed_dim: 192
#       depth: 4
#     loss_fn:
#       _target_: torch.nn.MSELoss

#   - _target_: tactile_ssl.probe.online_probe.OnlineProbeModule
#     probe_name: "object_classification"
#     decoder:
#       _target_: tactile_ssl.probe.classification.LinearClassifier
#       input_embed_dim: ${model_embed_dim}
#       classes: ${data.object_classes}
#       class_weights: ${data.object_class_weights}
#     loss_fn:
#       _partial_: true
#       _target_: torch.nn.CrossEntropyLoss

# online_probes_lrs: [1e-4, 1e-4]
# reconstruction_log_freq: 20
