#@package _global_

task_name: t1_force
model_size: tiny
sensors: image_audio_imu
model_embed_dim: ${model_info.${model_size}.embed_dim}
sensor_used: ${d360_modal_used_tag:${d360_modal_tag:${use_img}, ${use_mic}, ${use_imu}, ${use_pressure}}, ${task.sensors}}
experiment_name: D360-DINO-${d360_expt_name:${use_img}, ${use_mic}, ${use_imu}, ${use_pressure}, ${model_size}, ${attn_cls}, ${fusion_type}}-${capitalize:${sensor_used}}-${data_info.${ssl_data}}-${train_data_budget}
checkpoint_encoder: ~
seed: 42

hydra:
  job:
    id: ${now:%Y.%m.%d}-${now:%H-%M}
  run:
    dir: ${paths.log_dir}/${experiment_name}/${hydra.job.id}

wandb:
  project: d360_${task_name}
  group: ${experiment_name}
  tags:
    - ${ssl_alg}
    - ${ssl_data}
    - ${model_size}_${model_embed_dim}
    - ${d360_modal_tag:${use_img}, ${use_mic}, ${use_imu}, ${use_pressure}}
    - ${sensor_used}
    - ${fusion_type}
    - ${attn_cls}

data:
  train_data_budget: ${train_data_budget}
  val_data_budget: ${val_data_budget}

trainer:
  max_epochs: 51
  validation_frequency: 5
  sanity_validate: true
  save_checkpoint_dir: ${paths.output_dir}/checkpoints
  checkpoint_interval_type: "log"
  max_task_checkpoints: 10
  save_probe_weights_only: True

task:
  _target_: tactile_ssl.downstream_task.D360ForceSLModule
  checkpoint_task: ~

  model_encoder:
    _target_: tactile_ssl.model.d360_transformer.dit_${model_size}
    use_img: ${use_img}
    use_mic: ${use_mic}
    use_imu: ${use_imu}
    use_pressure: ${use_pressure}
    sensor_sizes: ${sensor_sizes}
    sensor_chans: ${sensor_chans}
    patch_sizes: ${patch_sizes}
    num_register_tokens: 1
    fusion_type: ${fusion_type}
    fusion_layer: 8
    num_bottlenecks: 4
    drop_path_rate: 0.3
    pos_embed_fn: learned
    normalization: ${data.dataset.config.normalization}
    attn_class:
      _partial_: True
      _target_: tactile_ssl.model.layers.${attn_cls}

  model_task:
    _target_: tactile_ssl.downstream_task.D360ForceLinearProbe
    embed_dim: ${model_embed_dim}
    num_heads: 12
    depth: 1
    with_last_activations: true
    attn_pooling: true
    only_normal_force: false

  sensors: ~
  checkpoint_encoder: ${checkpoint_encoder}
  train_encoder: false
  encoder_type: ${ssl_alg}
  supervise_delta_force: false

  optim_cfg:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001

  scheduler_cfg: ~
